server:
  port: 8086

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5433/catalog_db?sslmode=disable
    username: shop_user
    password: shop_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    jwt:
      secret: tWsUR+YBSTYgBZg4/wkbGHYh4g72VOFIlF76SNWEK0I7rGYKJ/ZPUVB/M/XlMq0d
      expirationMs: 86400000